# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-LinkChanger
version:      2.4
version_from: lib/HTML/LinkChanger.pm
installdirs:  site
requires:
    HTML::Parser:                  3
    HTML::Tagset:                  3
    URI:                           1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
